//! `usagi init`: bootstrap a new project. Templates are baked into the
//! binary at build time via `include_str!`, so the docs and LSP stubs in
//! a freshly-init'd project always match the version of `usagi` that
//! created it.

use crate::{Error, Result};
use std::fs;
use std::path::Path;

const MAIN_LUA: &str = include_str!("../templates/init/main.lua");
// The engine repo dogfoods its own .luarc.json; reuse it as the user
// template so config improvements flow into new projects automatically.
const LUARC_JSON: &str = include_str!("../.luarc.json");
const GITIGNORE: &str = include_str!("../templates/init/gitignore");
const META_USAGI_LUA: &str = include_str!("../meta/usagi.lua");
const README_MD: &str = include_str!("../README.md");

/// Writes the bootstrap files into `path`. Skips files that already
/// exist so re-running on an in-progress project never clobbers user
/// edits.
pub fn run(path: &str) -> Result<()> {
    let dir = Path::new(path);
    fs::create_dir_all(dir).map_err(|e| Error::Cli(format!("creating {}: {e}", dir.display())))?;
    fs::create_dir_all(dir.join("meta"))
        .map_err(|e| Error::Cli(format!("creating {}: {e}", dir.join("meta").display())))?;

    let stamped_meta = stamp_meta_lua(META_USAGI_LUA);
    let stamped_readme = stamp_readme(README_MD);
    let entries: &[(&str, &str)] = &[
        ("main.lua", MAIN_LUA),
        (".luarc.json", LUARC_JSON),
        (".gitignore", GITIGNORE),
        ("USAGI.md", &stamped_readme),
        ("meta/usagi.lua", &stamped_meta),
    ];
    let mut created = 0usize;
    let mut skipped = 0usize;
    for (rel, contents) in entries {
        let target = dir.join(rel);
        if target.exists() {
            println!("[usagi] skipped {rel} (already exists)");
            skipped += 1;
        } else {
            fs::write(&target, contents)
                .map_err(|e| Error::Cli(format!("writing {}: {e}", target.display())))?;
            println!("[usagi] created {rel}");
            created += 1;
        }
    }

    println!(
        "[usagi] initialized at {} ({created} created, {skipped} skipped)",
        dir.display()
    );
    if created > 0 {
        let next = if path == "." {
            "usagi dev".to_string()
        } else {
            format!("usagi dev {path}")
        };
        println!("[usagi]   next: {next}");
    }
    Ok(())
}

/// Injects a version stamp on line 2 of the meta file (after `---@meta`).
/// The repo's `meta/usagi.lua` stays clean; the stamp only appears in
/// generated copies, so users can tell which usagi version produced
/// theirs.
fn stamp_meta_lua(source: &str) -> String {
    let stamp = format!(
        "-- Generated by usagi {}. Delete this file and re-run `usagi init` to refresh.\n",
        env!("CARGO_PKG_VERSION"),
    );
    match source.split_once('\n') {
        Some((first, rest)) => format!("{first}\n{stamp}{rest}"),
        None => format!("{stamp}{source}"),
    }
}

/// Stamps the README with an HTML comment so it doesn't render. Sits
/// above the title so anyone opening the file sees the version
/// immediately.
fn stamp_readme(source: &str) -> String {
    format!(
        "<!-- Generated by usagi {}. Delete this file and re-run `usagi init` to refresh. -->\n\n{source}",
        env!("CARGO_PKG_VERSION"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn writes_all_template_files() {
        let dir = tempdir().unwrap();
        run(dir.path().to_str().unwrap()).unwrap();
        assert!(dir.path().join("main.lua").is_file());
        assert!(dir.path().join(".luarc.json").is_file());
        assert!(dir.path().join(".gitignore").is_file());
        assert!(dir.path().join("USAGI.md").is_file());
        assert!(dir.path().join("meta/usagi.lua").is_file());
    }

    #[test]
    fn does_not_clobber_existing_files() {
        let dir = tempdir().unwrap();
        let main = dir.path().join("main.lua");
        fs::write(&main, b"-- user content").unwrap();
        run(dir.path().to_str().unwrap()).unwrap();
        assert_eq!(fs::read(&main).unwrap(), b"-- user content");
    }

    #[test]
    fn idempotent_on_rerun() {
        let dir = tempdir().unwrap();
        run(dir.path().to_str().unwrap()).unwrap();
        let main_before = fs::read(dir.path().join("main.lua")).unwrap();
        run(dir.path().to_str().unwrap()).unwrap();
        let main_after = fs::read(dir.path().join("main.lua")).unwrap();
        assert_eq!(main_before, main_after);
    }

    #[test]
    fn creates_target_dir_when_missing() {
        let parent = tempdir().unwrap();
        let nested = parent.path().join("new-game");
        run(nested.to_str().unwrap()).unwrap();
        assert!(nested.join("main.lua").is_file());
    }

    #[test]
    fn meta_lua_keeps_meta_annotation_on_line_one() {
        let stamped = stamp_meta_lua("---@meta\n-- existing comment\nfoo = 1\n");
        let mut lines = stamped.lines();
        assert_eq!(lines.next(), Some("---@meta"));
        let stamp_line = lines.next().unwrap();
        assert!(stamp_line.starts_with("-- Generated by usagi"));
        assert!(stamp_line.contains(env!("CARGO_PKG_VERSION")));
    }

    #[test]
    fn readme_stamp_is_html_comment_at_top() {
        let stamped = stamp_readme("# Title\n\nbody\n");
        let first = stamped.lines().next().unwrap();
        assert!(first.starts_with("<!-- Generated by usagi"));
        assert!(first.contains(env!("CARGO_PKG_VERSION")));
        assert!(first.ends_with("-->"));
    }

    #[test]
    fn written_meta_lua_contains_version_stamp() {
        let dir = tempdir().unwrap();
        run(dir.path().to_str().unwrap()).unwrap();
        let meta = fs::read_to_string(dir.path().join("meta/usagi.lua")).unwrap();
        assert!(meta.starts_with("---@meta\n"));
        assert!(
            meta.lines()
                .nth(1)
                .unwrap()
                .contains(env!("CARGO_PKG_VERSION"))
        );
    }
}
